/* GENERATED by nucleus-server/scripts/brand/generate.mjs — do not edit by hand.
 * Source of truth: nucleus-server/scripts/brand/mark.mjs. Re-run `npm run brand:generate`. */

export type NucleusPaletteKey = 'p1' | 'p2' | 'o1' | 'o2' | 'c1' | 'c2' | 'c3' | 'wordmark';
export type NucleusPalette = Record<NucleusPaletteKey, string>;
export type NucleusTone = 'light' | 'dark' | 'white' | 'mono';

/** The 760-unit canvas every mark path is drawn in (centre at the origin). */
export const NUCLEUS_VIEWBOX = '-380 -380 760 760';
export const NUCLEUS_CANVAS = 760;

export const NUCLEUS_PALETTES: Record<NucleusTone, NucleusPalette> = {
  light: {
    p1: '#3e0db5',
    p2: '#7a35d0',
    o1: '#ff9e08',
    o2: '#ff8a1c',
    c1: '#8b47d3',
    c2: '#4b249b',
    c3: '#1a1560',
    wordmark: '#041d55',
  },
  dark: {
    p1: '#7b58f5',
    p2: '#a98cff',
    o1: '#ffa826',
    o2: '#ff8f2e',
    c1: '#c9b0ff',
    c2: '#7b58f5',
    c3: '#3a2190',
    wordmark: '#f4f4f5',
  },
  white: {
    p1: '#ffffff',
    p2: '#efe8ff',
    o1: '#ffb020',
    o2: '#ff9a1c',
    c1: '#ffffff',
    c2: '#efe8ff',
    c3: '#c9b6ff',
    wordmark: '#ffffff',
  },
  mono: {
    p1: '#ffffff',
    p2: '#ffffff',
    o1: '#ffffff',
    o2: '#ffffff',
    c1: '#ffffff',
    c2: '#ffffff',
    c3: '#ffffff',
    wordmark: '#ffffff',
  },
};

/** Employee app tile — deep purple diagonal gradient (top-left → bottom-right). */
export const NUCLEUS_EMPLOYEE_TILE = {
  from: '#2a0a7a',
  to: '#4c16c9',
  solid: '#3a0fa0',
};

export interface NucleusGradientStop {
  offset: number;
  tone: NucleusPaletteKey;
}
export interface NucleusLinearGradient {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  stops: NucleusGradientStop[];
}
export interface NucleusRadialGradient {
  cx: number;
  cy: number;
  r: number;
  fx: number;
  fy: number;
  stops: NucleusGradientStop[];
}
export interface NucleusElectron {
  x: number;
  y: number;
  r: number;
  tone: NucleusPaletteKey;
}
export interface NucleusMarkGeometry {
  stroke: number;
  coreRadius: number;
  paths: {
    outerPurple: string;
    outerOrange: string;
    innerPurple?: string;
    innerBlend?: string;
  };
  gradients: {
    outerPurple: NucleusLinearGradient;
    outerOrange: NucleusLinearGradient;
    innerPurple?: NucleusLinearGradient;
    innerBlend?: NucleusLinearGradient;
    core: NucleusRadialGradient;
  };
  electrons: NucleusElectron[];
}

/** The full mark: two rings, gradient core, four electrons. */
export const NUCLEUS_MARK: NucleusMarkGeometry = {
  stroke: 26,
  coreRadius: 116,
  paths: {
    outerPurple: 'M 164.23 -255.82 A 304 304 0 1 0 225.92 203.42',
    outerOrange: 'M 236.25 191.31 A 304 304 0 0 0 289.93 -91.41',
    innerPurple: 'M 100.32 -163.71 A 192 192 0 0 0 -186.77 44.5',
    innerBlend: 'M -153.94 114.74 A 192 192 0 1 0 140.42 -130.94',
  },
  gradients: {
    outerPurple: {
      x1: -263.27,
      y1: -152,
      x2: 128.48,
      y2: -275.52,
      stops: [
        {
          offset: 0,
          tone: 'p1',
        },
        {
          offset: 0.35,
          tone: 'p1',
        },
        {
          offset: 1,
          tone: 'p2',
        },
      ],
    },
    outerOrange: {
      x1: 236.25,
      y1: 191.31,
      x2: 289.93,
      y2: -91.41,
      stops: [
        {
          offset: 0,
          tone: 'o2',
        },
        {
          offset: 0.4,
          tone: 'o1',
        },
        {
          offset: 1,
          tone: 'o1',
        },
      ],
    },
    core: {
      cx: 0.62,
      cy: 0.36,
      r: 0.78,
      fx: 0.68,
      fy: 0.28,
      stops: [
        {
          offset: 0,
          tone: 'c1',
        },
        {
          offset: 0.45,
          tone: 'c2',
        },
        {
          offset: 1,
          tone: 'c3',
        },
      ],
    },
    innerPurple: {
      x1: -166.28,
      y1: -96,
      x2: 96,
      y2: -166.28,
      stops: [
        {
          offset: 0,
          tone: 'p1',
        },
        {
          offset: 0.55,
          tone: 'p1',
        },
        {
          offset: 1,
          tone: 'p2',
        },
      ],
    },
    innerBlend: {
      x1: 0,
      y1: 192,
      x2: 192,
      y2: 0,
      stops: [
        {
          offset: 0,
          tone: 'p1',
        },
        {
          offset: 0.48,
          tone: 'p1',
        },
        {
          offset: 0.82,
          tone: 'o2',
        },
        {
          offset: 1,
          tone: 'o1',
        },
      ],
    },
  },
  electrons: [
    {
      x: -259.76,
      y: -157.93,
      r: 40,
      tone: 'p1',
    },
    {
      x: -288.79,
      y: 94.95,
      r: 50,
      tone: 'p1',
    },
    {
      x: 208.1,
      y: 221.61,
      r: 28,
      tone: 'p1',
    },
    {
      x: 241.5,
      y: -184.64,
      r: 55,
      tone: 'o1',
    },
  ],
};

/** Simplified mark for tiny renders (≤ 32 px). */
export const NUCLEUS_MARK_SMALL: NucleusMarkGeometry = {
  stroke: 72,
  coreRadius: 140,
  paths: {
    outerPurple: 'M 117.22 -276.15 A 300 300 0 1 0 208.4 215.8',
    outerOrange: 'M 248.71 167.76 A 300 300 0 0 0 297.22 -40.71',
  },
  gradients: {
    outerPurple: {
      x1: -259.81,
      y1: -150,
      x2: 126.79,
      y2: -271.89,
      stops: [
        {
          offset: 0,
          tone: 'p1',
        },
        {
          offset: 0.35,
          tone: 'p1',
        },
        {
          offset: 1,
          tone: 'p2',
        },
      ],
    },
    outerOrange: {
      x1: 233.14,
      y1: 188.8,
      x2: 297.22,
      y2: -40.71,
      stops: [
        {
          offset: 0,
          tone: 'o2',
        },
        {
          offset: 0.4,
          tone: 'o1',
        },
        {
          offset: 1,
          tone: 'o1',
        },
      ],
    },
    core: {
      cx: 0.62,
      cy: 0.36,
      r: 0.78,
      fx: 0.68,
      fy: 0.28,
      stops: [
        {
          offset: 0,
          tone: 'c1',
        },
        {
          offset: 0.45,
          tone: 'c2',
        },
        {
          offset: 1,
          tone: 'c3',
        },
      ],
    },
  },
  electrons: [
    {
      x: -256.34,
      y: -155.86,
      r: 46,
      tone: 'p1',
    },
    {
      x: -284.99,
      y: 93.7,
      r: 58,
      tone: 'p1',
    },
    {
      x: 238.32,
      y: -182.21,
      r: 66,
      tone: 'o1',
    },
  ],
};

/**
 * Loader animation: each ring revolves *with* its own electrons as one rigid
 * group about the still core, so a ring's gaps always sit where the logo puts
 * them and no electron is ever stranded in one. The outer group carries the
 * ring plus all four electrons at their logo angles; the inner ring spins bare
 * and the other way — its two gaps are what make its motion readable. The first
 * frame is therefore pixel-identical to the static logo.
 */
export const NUCLEUS_ORBIT_PERIODS_MS = {
  outer: 4000,
  inner: 1800,
} as const;

/** Turn direction per ring: 1 = clockwise, -1 = anticlockwise. */
export const NUCLEUS_ORBIT_DIRECTIONS = {
  outer: 1,
  inner: -1,
} as const;
